# Config file for automatic testing at travis-ci.com

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - 3.8
  - 3.7
  - 3.6
  
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda update -c conda-forge conda
  
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment -c conda-forge python=$TRAVIS_PYTHON_VERSION numpy scipy  pandas matplotlib gdal geopandas shapely fiona rasterio pyproj cartopy descartes utm
  - conda activate test-environment
  - python setup.py install

script: plotbasicrasters -h
  
